language: go
sudo: true
go:
  - 1.7
  - 1.8
go_import_path: github.com/uber/zanzibar
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
before_install:
  - sudo apt-get install -qq time
  - sudo apt-get install -qq wrk
install:
  - make install
script:
  - make generate
  - make lint
  - make test-only
  - make cover
  - make fast-bench
  - make bins
  - make test-benchmark-runner
after_success:
  - make travis-coveralls
