# Add your production configuration here
serviceName: example-gateway
ip: 127.0.0.1
port: 7783

# jaeger:
#   disabled: false

logger:
  fileName: /var/log/example-gateway/example-gateway.log

metrics:
  tally:
    flushInterval: 1s
  m3:
    hostPort: 127.0.0.1:9052
    service: example-gateway
    flushInterval: 500ms

tchannel:
  serviceName: example-gateway
  processName: example-gateway

clients:
  contacts:
    port: 4000
    ip: 127.0.0.1
  googleNow:
    port: 14120
    ip: 127.0.0.1
